apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: frontend-doc
  name: frontend-doc
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend-doc
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/doc-frontend-default: "true"
        io.kompose.service: frontend-doc
    spec:
      containers:
        - image: frontend:v2
          name: assignment-frontend-container
          ports:
            - containerPort: 3030
              hostPort: 3030
              protocol: TCP
      restartPolicy: Always
